version: "3.9"
services:
  react:
    container_name: pomodoros-react
    build:
      context: ./front
      target: development
    volumes:
      - ./front:/app
      - modules:/app/node_modules/
    ports:
      - "5173:5173"
volumes:
  modules: